### PR TITLE
fix ring & update

### PR DESCRIPTION
**Pull request by DeinFreund**

### CODE REVIEW

**Comment by db81** [comment]
If NeedReadyResponse is false I think the intention is that you still show the message. So I guess just Log.infoBox() it in that case.

**Comment by DeinFreund** [comment]
Licho isn't sure about that himself from what I understood. If that was implemented it would show an info box after clicking accept, to inform you that you clicked accept.

**Comment by db81** [comment]
There's ZeroK-RTS/Zero-K-Infrastructure#1197 now, I think we can wait on it for a bit while the protocol is in a flux.

**Comment by DeinFreund** [comment]
Outdated.

**Pull request closed without merging**
