### PR TITLE
move username to own object

### PR DESCRIPTION
**Pull request by DeinFreund**
->

The rank icon is only displayed when logged in.

### CODE REVIEW

**Comment by Anarchid** [comment]
Does this cause the thing to jump? If so , that's bad (but i guess you could add a css transition to make it less bad).

**Comment by db81** [comment]
Eh fine, just do what you did originally, the user label in place of the button, and find another icon for offline state à la https://d30y9cdsu7xlg0.cloudfront.net/png/4032-200.png and change the label to Offline when we're not connected.

**Comment by Anarchid** [comment]
If the connection button becomes replaced with user label, then it should display a dropdown when being clicked ("DeinFreund -> Logout") IMO

**Comment by db81** [comment]
Maybe a popup that says "Click to logout", or an icon like this one at the end:

**Comment by Anarchid** [comment]
In context of ZK there could be other things to do to the player, like view their profile, etc.

**Comment by DeinFreund** [comment]
Having a Player button could be useful as profile link later. But if you want to add more things as a direct dropdown anyway, there's no advantage of having the extra button.

Keep in mind that any kind of pop-up/dropdown makes the interface slower to use and feel less elegant.

**Comment by db81** [comment]
I think we can do the simple button now, and worry about dropdowns later. I'm not sure a profile button is even useful (for some newbies, maaybe, but that's not quite our niche).

I think the socket icon is different enough from rank icons to not be confusing. Renaming the button to "Offline" was a dumb idea of mine though, so keep the label.

**Pull request closed without merging**
