### PR TITLE
Shiny new rank icons! (+ bonus Create Battle UI)

### PR DESCRIPTION
**Pull request by DeinFreund**
user
klon
ranks

Added attributes user.elo, user.elo1v1 and user.level

### CODE REVIEW

**Comment by DeinFreund** [comment]
On spring the shade defaults to 2. Is there anything that it could be used for there?
spring

**Comment by DeinFreund** [comment]
Sorry i cant into git

**Comment by db81** [comment]
For the future, make separate topic branches and separate PRs from them for every feature, not a big composite PR.

**Comment by DeinFreund** [comment]
Yup, this was not intended to end up like this.. :/

**Pull request merged**
